### ISSUE TITLE
Protocol 0.2.6

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/python-ogn-client#20]
Since Flarm Technology GmbH again changed the flarm encryption and made it mandantory to use the ogn software 0.2.6 we should drop drop compatibility to receiver protocol < 0.2.6

**Comment by kerel-fs** [comment]
Why?
OGN-Trackers received with software version <v0.2.6 are still working.

**Comment by Meisterschueler** [comment]
Right... I forgot the trackers...
