### ISSUE TITLE
Unable to disconnect from OGN data stream

### ISSUE THREAD

**Issue by akolar** [glidernet/python-ogn-client#27]
When an AprsClient is started in autoreconnect mode it is impossible to disconnect/exit the main loop of the AprsClient.run() function.

Minimal example
```
import signal

from ogn.client import AprsClient
from ogn.parser import parse_aprs, parse_ogn_beacon, ParseError

def process_beacon(raw_message):
    print('Received message')

client = AprsClient(aprs_user='N0CALL')
signal.signal(signal.SIGTERM, lambda signo, stackno: client.disconnect())
client.connect()
client.run(callback=process_beacon, autoreconnect=True)
```

The above script cannot be killed with `kill <PID>` because after disconnecting from the OGN datastream the client will be automatically reconnected after handling the exception caused by the broken connection.  

This causes difficulties when running the client inside threads or in background because the process cannot be exited in a simple manner.

Pull request #26 fixes such issues by adding a kill flag that serves as an exit condition to both loops inside AprsClient.run().

**Comment by Meisterschueler** [comment]
Pull request #26 .
