### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by vranki** [glidernet/python-ogn-client#70]
I've got python 3.7 pipenv environment.

I've installed ogn-client with pip. 

Running the second example in README results in:

```python
Traceback (most recent call last):
  File "ogn.py", line 1, in <module>
    from ogn.client import AprsClient
  File "/home/cos/src/ogntest/ogn.py", line 1, in <module>
    from ogn.client import AprsClient
ModuleNotFoundError: No module named 'ogn.client'; 'ogn' is not a package
```
Any ideas?

**Comment by Meisterschueler** [comment]
Hi @vranki , could you please double check if you installed ogn-client 0.9.6 correctly?

**Comment by clementallen** [comment]
@vranki could this be because your file is also called `ogn.py`?  Perhaps try naming it something different

**Comment by vranki** [comment]
Yes, looks like naming the test app ogn.py causes the issue. I got the app to print out messages after renaming the file to something else. Sorry.
