### ISSUE TITLE
reference_timestamp is utc.zone ignorant in ogn Parser

### ISSUE THREAD

**Issue by lemoidului** [glidernet/python-ogn-client#84]
in parse function, reference_timstamp is None by default.
timestamp return is calculated on datetime.utcnow() in this case.
If your machine is set on utc zone != 0 and you need POSIX timestamp, you have to do:
posix_timestamp = parser_timestamp.replace(tzinfo=timezone.utc).timestamp()
as describe in Python doc: https://docs.python.org/fr/3/library/datetime.html#datetime.datetime.timestamp
Solution should be to provided timezone info in reference_timestamp
ie: parse(raw_message, reference_timestamp=datetime.now(timezone.utc))
but in this case, the CreateTimestamp function fail during comparison:
result > reference_timestamp + timedelta(...)
or
result < reference_timestamp - timedelta(...)
resust is first create with datetime() but is unaware of reference_timestamp timezone.

**Comment by Meisterschueler** [comment]
If I understand you correctly you want to use a reference_timestamp with tzinfo != None
